# Generated by Django 4.1.7 on 2023-03-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
